version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: main
    env_file: .env
    volumes:
      - ./api:/jellness-api/api
    command: go run server.go
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
volumes:
  db-data:
